import { chromium } from '@playwright/test';
import { installBackendMock, freezeAnimations } from '../../e2e/support/backendMock.js';
const game = process.argv[2] || 'chain';
const out = process.argv[3] || 'claude/card-polish/zoom';
import fs from 'fs'; fs.mkdirSync(out, { recursive: true });
const b = await chromium.launch();
const ctx = await b.newContext({ baseURL:'http://localhost:4173', viewport:{width:1280,height:900}, deviceScaleFactor:3 });
const p = await ctx.newPage(); await installBackendMock(p);
await p.addInitScript(()=>{ try{ localStorage.setItem('taw.xp', JSON.stringify({lv:40,into:0})); }catch{} });
await p.goto('/?portal=1'); await p.getByRole('img',{name:'Type a Word'}).waitFor(); await freezeAnimations(p); await p.waitForTimeout(400);
const card = p.locator(`.game-card-magnet[data-game="${game}"] .game-card`);
await card.screenshot({ path: `${out}/${game}.png` });
await b.close(); console.log(`${game} ->`, out);
