import { chromium } from '@playwright/test';
import { installBackendMock } from '../../e2e/support/backendMock.js';
const ME='e2e-player';
const wbPlayers=[{id:ME,name:'YOU',lives:3,isHost:true},{id:'p2',name:'RIVAL',lives:2}];
const b=await chromium.launch();
const ctx=await b.newContext({baseURL:'http://localhost:4173',viewport:{width:390,height:844}});
const p=await ctx.newPage(); const mock=await installBackendMock(p);
await p.goto('/?portal=1'); await p.getByRole('img',{name:'Type a Word'}).waitFor();
mock.pushToClient({type:'room_update',payload:{code:'WXYZ',gameType:'word-bomb',hostId:ME,difficultyKey:'chill',players:wbPlayers}}); await p.waitForTimeout(80);
mock.pushToClient({type:'game_started',payload:{gameType:'word-bomb'}}); await p.waitForTimeout(80);
mock.pushToClient({type:'turn_update',payload:{currentPlayerId:ME,players:wbPlayers,combo:'at',usedWords:['CAT','BAT'],timerSeconds:22}});
await p.waitForTimeout(3500);
console.log('BEFORE drop: connlost overlay =', await p.locator('.connlost-overlay').count(), '| board =', await p.locator('.game-player-bar').count());
mock.dropClient();
await p.waitForTimeout(2500);
const connlost = await p.locator('.connlost-overlay').isVisible().catch(()=>false);
const title = (await p.locator('.connlost-title').textContent().catch(()=>''))||'';
const sub = (await p.locator('.connlost-sub').textContent().catch(()=>''))||'';
const btn = (await p.locator('.connlost-btn').textContent().catch(()=>''))||'';
const boardStill = await p.locator('.game-player-bar').count();
const attempts = mock.connectionAttempts ? mock.connectionAttempts() : '?';
console.log('AFTER drop 2.5s: connlost=',connlost,'| title=',JSON.stringify(title.trim()),'| sub=',JSON.stringify(sub.trim().slice(0,80)),'| action=',JSON.stringify(btn.trim()),'| boardBehind=',boardStill,'| reconnectAttempts=',attempts);
await p.screenshot({path:'claude/reconnect-shots/before-drop.png'});
await b.close();
