// texture.test.js — BUILD-FAILING guard for the grain / halftone surface
// (theme/texture.css). Grain is a fullscreen repeating bitmap generated by an SVG
// filter. Painted once on a static layer it is free; painted on anything that MOVES
// it becomes a fullscreen repaint every frame, which is the single most expensive
// mistake available in this codebase. These assertions make that impossible to add
// by accident.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC = join(dirname(fileURLToPath(import.meta.url)), '..');
const norm = (p) => p.split('\\').join('/');

function cssFiles(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...cssFiles(p));
    else if (name.endsWith('.css')) out.push(p);
  }
  return out;
}
const strip = (css) => css.replace(/\/\*[\s\S]*?\*\//g, (m) => ' '.repeat(m.length));
function rules(css) {
  const out = [];
  const re = /([^{}]+)\{([^{}]*)\}/g;
  let m;
  while ((m = re.exec(css)) !== null) out.push({ sel: m[1].trim().replace(/\s+/g, ' '), body: m[2], index: m.index });
  return out;
}
const lineOf = (css, i) => css.slice(0, i).split('\n').length;

test('the grain is never painted on an animated element', () => {
  const offenders = [];
  for (const file of cssFiles(SRC)) {
    const css = strip(readFileSync(file, 'utf8'));
    for (const r of rules(css)) {
      if (!/var\(--tx-grain\)/.test(r.body)) continue;
      // An `animation` (or a transition on anything but opacity) on the SAME rule that
      // paints the grain means the grain bitmap is re-rasterised as the element moves.
      if (/(^|[;{\s])animation(-name)?\s*:/i.test(r.body) && !/animation[^:]*:\s*none/i.test(r.body)) {
        offenders.push(`${norm(file)}:${lineOf(css, r.index)}  ${r.sel} animates AND paints the grain`);
      }
      const tr = r.body.match(/(^|[;{\s])transition\s*:\s*([^;]+)/i);
      if (tr && !/^\s*(none|opacity\b)/i.test(tr[2])) {
        offenders.push(`${norm(file)}:${lineOf(css, r.index)}  ${r.sel} transitions "${tr[2].trim()}" AND paints the grain`);
      }
      // transform on a grain-painting rule = the bitmap moves with it.
      if (/(^|[;{\s])transform\s*:\s*(?!none)/i.test(r.body)) {
        offenders.push(`${norm(file)}:${lineOf(css, r.index)}  ${r.sel} is transformed AND paints the grain`);
      }
    }
  }
  assert.equal(
    offenders.length, 0,
    `The grain must sit on a STATIC layer - it is a fullscreen bitmap and moving it repaints it every frame:\n${offenders.join('\n')}`
  );
});

test('the grain is an inline data-URI, never a network request', () => {
  const css = strip(readFileSync(join(SRC, 'theme', 'texture.css'), 'utf8'));
  const m = css.match(/--tx-grain:\s*url\((["']?)(.*?)\1\)/s);
  assert.ok(m, '--tx-grain is not defined');
  const uri = m[2];
  assert.ok(uri.startsWith('data:image/svg+xml'), 'the grain must be an inline SVG data-URI (no network fetch)');
  assert.ok(/feTurbulence/.test(uri), 'the grain should be feTurbulence noise');
  assert.ok(/feColorMatrix/.test(uri), 'the grain should be desaturated to a single hue via feColorMatrix');
  // Keep it small: it ships inside the CSS bundle on every page load.
  assert.ok(uri.length < 600, `the grain data-URI is ${uri.length} bytes, keep it under 600`);
});

test('grain opacity stays in the 6-10% band and halftone in 10-20%', () => {
  const css = strip(readFileSync(join(SRC, 'theme', 'texture.css'), 'utf8'));
  const g = css.match(/--tx-grain-opacity:\s*([\d.]+)/);
  assert.ok(g, '--tx-grain-opacity is not defined');
  const gv = parseFloat(g[1]);
  assert.ok(gv >= 0.06 && gv <= 0.1, `--tx-grain-opacity is ${gv}, must be within 0.06-0.10`);

  const h = css.match(/--tx-halftone-ink:\s*rgba\([^)]*?,\s*([\d.]+)\s*\)/);
  assert.ok(h, '--tx-halftone-ink is not defined');
  const hv = parseFloat(h[1]);
  assert.ok(hv >= 0.1 && hv <= 0.2, `--tx-halftone-ink alpha is ${hv}, must be within 0.10-0.20`);
});

test('the halftone stays off text-bearing panels', () => {
  // These panels carry body copy. A dot screen under running text eats the contrast
  // the type scale bought, so the halftone is hero-shapes-only. (The mode CARD is a
  // hero shape and is allowed - its text sits on its own bars, not on the dot field.)
  const TEXT_PANELS = [
    '.game-stage', '.kill-feed', '.credits-panel', '.shop-panel', '.stats-panel',
    '.mode-dialog-content', '.game-used', '.room-box',
  ];
  const offenders = [];
  for (const file of cssFiles(SRC)) {
    const css = strip(readFileSync(file, 'utf8'));
    for (const r of rules(css)) {
      const paintsDots = /var\(--tx-halftone-ink\)/.test(r.body)
        || /background-image\s*:\s*radial-gradient\([^;]*\)\s*;?/i.test(r.body);
      if (!paintsDots) continue;
      if (!/radial-gradient/i.test(r.body)) continue;
      for (const panel of TEXT_PANELS) {
        if (r.sel === panel || r.sel.startsWith(panel + ' ') || r.sel.startsWith(panel + '.')) {
          offenders.push(`${norm(file)}:${lineOf(css, r.index)}  ${r.sel} paints a dot screen under body copy`);
        }
      }
    }
  }
  assert.equal(
    offenders.length, 0,
    `The halftone is for large flat HERO shapes only:\n${offenders.join('\n')}`
  );
});
