// claude/wordlists/measure.mjs — STEP 55: how often does each mode REJECT a common real word?
//
// Run (from repo root):  node claude/wordlists/measure.mjs claude/wordlists/after.json
// Re-runnable; reads only committed assets. Also (re)writes claude/wordlists/probe.txt.
//
// ACCEPT SETS — replicated exactly as src/solo/words.js builds them:
//   firstRun = RECALL ∪ words.accept.txt ∪ words.famous.txt ∪ words.common.txt (if present)
//   merged   = firstRun ∪ words.accept-ext.txt   (lazy extension, lands AFTER the first run ends)
// FUSE rule (fuse.js validate): word contains the fragment, not used, accept.has(word).
// CHAIN rule (chain.js validate): length >= 3, starts with the required letter, accept.has(word).
// So for a probe word the only reject a player can't control is NOT_IN_LIST — that is what we count.
//
// WORD BOMB is judged by the BACKEND (chain-reaction-backend/dictionary.js), which this repo does not
// change. If that checkout is present beside this one, its verdict is measured READ-ONLY for context.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { createRequire } from 'node:module';
import { CATEGORIES } from './categories.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..', '..');
const SOLO = join(ROOT, 'src', 'solo');
const read = (f) => readFileSync(join(SOLO, f), 'utf8');

// ---- accept sets -------------------------------------------------------------------------------
const recall = read('words.recall.txt').split(' ');
const firstRun = new Set(recall);
for (const w of read('words.accept.txt').split(' ')) firstRun.add(w);
for (const w of read('words.famous.txt').split(/\s+/)) if (w) firstRun.add(w.toLowerCase());
const hasCommon = existsSync(join(SOLO, 'words.common.txt'));
if (hasCommon) for (const w of read('words.common.txt').split(/\s+/)) if (w) firstRun.add(w.toLowerCase());
const merged = new Set(firstRun);
for (const w of read('words.accept-ext.txt').split(' ')) if (w) merged.add(w);

// ---- probe set ---------------------------------------------------------------------------------
// Hand-curated categories + the 3000 most frequent RECALL words (index === frequency rank).
const probeCats = { ...CATEGORIES, common_top3000: recall.slice(0, 3000) };
const probeCat = new Map(); // word -> first category
for (const [cat, words] of Object.entries(probeCats)) {
  for (const w of words) if (/^[a-z]{3,}$/.test(w) && !probeCat.has(w)) probeCat.set(w, cat);
}
const probe = [...probeCat.keys()];
writeFileSync(join(__dirname, 'probe.txt'),
  '# STEP 55 probe — word<TAB>category. Generated by measure.mjs from categories.mjs + recall top-3000.\n' +
  probe.map((w) => `${w}\t${probeCat.get(w)}`).join('\n') + '\n');

// ---- per-mode measurement ----------------------------------------------------------------------
const pools = JSON.parse(read('fragmentPools.json'));
const frags = [];
for (const [tier, s] of Object.entries(pools)) for (const f of String(s).trim().split(/\s+/)) frags.push({ tier, f });

function fuse(accept) {
  const perTier = {};
  let affected = 0, withAny = 0;
  const worst = [];
  for (const { tier, f } of frags) {
    const t = (perTier[tier] ||= { fragments: 0, withProbe: 0, affected: 0, probeHits: 0, rejectedHits: 0 });
    t.fragments++;
    const hits = probe.filter((w) => w.includes(f));
    const rej = hits.filter((w) => !accept.has(w));
    t.probeHits += hits.length;
    t.rejectedHits += rej.length;
    if (hits.length) { t.withProbe++; withAny++; }
    if (rej.length) { t.affected++; affected++; worst.push({ f, tier, rejected: rej.length, of: hits.length, sample: rej.slice(0, 6) }); }
  }
  worst.sort((a, b) => b.rejected - a.rejected);
  return {
    fragments: frags.length,
    fragmentsWithAProbeWord: withAny,
    fragmentsWithARejectedCommonWord: affected,
    pctFragmentsAffected: +(100 * affected / frags.length).toFixed(1),
    perTier,
    worstFragments: worst.slice(0, 15),
  };
}

function rejectStats(accept) {
  const byCat = {};
  const rejected = [];
  for (const w of probe) {
    const c = probeCat.get(w);
    const b = (byCat[c] ||= { probe: 0, rejected: 0, pct: 0, sample: [] });
    b.probe++;
    if (!accept.has(w)) { b.rejected++; rejected.push(w); if (b.sample.length < 12) b.sample.push(w); }
  }
  for (const b of Object.values(byCat)) b.pct = +(100 * b.rejected / b.probe).toFixed(1);
  return { probeWords: probe.length, rejected: rejected.length, pctRejected: +(100 * rejected.length / probe.length).toFixed(1), byCategory: byCat };
}

function chain(accept) {
  // Per required letter: share of letters for which some common probe word starting with it is rejected.
  const letters = {};
  for (const w of probe) {
    const l = (letters[w[0]] ||= { probe: 0, rejected: 0 });
    l.probe++;
    if (!accept.has(w)) l.rejected++;
  }
  const affected = Object.values(letters).filter((l) => l.rejected).length;
  return { ...rejectStats(accept), lettersAffected: affected, letters: Object.keys(letters).length };
}

// Word Bomb (backend, READ-ONLY). Optional.
function wordBomb() {
  const be = resolve(ROOT, '..', '..', '..', '..', 'chain-reaction-backend');
  const alt = 'C:/Users/andyw_tnc0kix/Downloads/chain-reaction-backend';
  const dir = existsSync(join(be, 'wordFilter.js')) ? be : existsSync(join(alt, 'wordFilter.js')) ? alt : null;
  if (!dir) return { skipped: 'backend checkout not found' };
  try {
    const req = createRequire(join(dir, 'package.json'));
    const { isDisallowedWord, isCommonEnglishWord } = req('./wordFilter.js');
    const { isSlur } = req('./blockedTerms.js');
    const ok = (w) => !isDisallowedWord(w) && !isSlur(w) && isCommonEnglishWord(w);
    const acc = { has: ok };
    const s = rejectStats(acc);
    const disallowed = probe.filter((w) => isDisallowedWord(w)).length;
    return { note: 'backend dictionary.js isValidWord logic, read-only; NOT changed by STEP 55', ...s, rejectedByPlaceNameBlocklist: disallowed };
  } catch (e) {
    return { skipped: String(e.message || e) };
  }
}

// Independent cross-check (NOT the probe): the top-25k a-z 3+ tokens of the Norvig web corpus that
// scripts/build-words.mjs caches in the OS temp dir. Mostly junk (html, usa, names, porn spam), so
// the absolute number means little — the before→after DELTA is a held-out signal for how many
// genuinely frequent tokens the new list rescued. Optional: skipped if the cache is absent.
async function corpusGap() {
  const { tmpdir } = await import('node:os');
  const f = join(tmpdir(), 'wa-count_1w.txt');
  if (!existsSync(f)) return { skipped: 'corpus cache not found (run scripts/build-words.mjs once)' };
  const toks = readFileSync(f, 'utf8').split('\n').slice(0, 25000).map((l) => l.split('\t')[0]).filter((w) => /^[a-z]{3,}$/.test(w));
  const miss = (acc) => toks.filter((w) => !acc.has(w));
  return { tokens: toks.length, rejectedFirstRun: miss(firstRun).length, rejectedMerged: miss(merged).length, sampleMerged: miss(merged).slice(0, 40) };
}

const out = {
  generatedAt: new Date().toISOString(),
  wordsCommonTxtPresent: hasCommon,
  acceptSizes: { firstRun: firstRun.size, merged: merged.size },
  probe: { total: probe.length, byCategory: Object.fromEntries(Object.entries(probeCats).map(([k, v]) => [k, v.length])) },
  FUSE: { firstRun: fuse(firstRun), merged: fuse(merged) },
  CHAIN: { firstRun: chain(firstRun), merged: chain(merged) },
  SAT_RUSH: 'N/A — SAT Rush asks for ONE known target word (engine.js wordMap); there is no open dictionary to expand.',
  WORD_BOMB_backend: wordBomb(),
  corpusTop25kGap: await corpusGap(),
};
const dest = process.argv[2] ? resolve(process.argv[2]) : join(__dirname, 'after.json');
writeFileSync(dest, JSON.stringify(out, null, 2) + '\n');
const F = out.FUSE, C = out.CHAIN;
console.log(`probe ${probe.length} words; accept firstRun ${firstRun.size}, merged ${merged.size}`);
console.log(`FUSE  firstRun: ${F.firstRun.pctFragmentsAffected}% fragments affected (${F.firstRun.fragmentsWithARejectedCommonWord}/${F.firstRun.fragments}); merged: ${F.merged.pctFragmentsAffected}%`);
console.log(`PROBE rejected firstRun: ${C.firstRun.pctRejected}% (${C.firstRun.rejected}); merged: ${C.merged.pctRejected}% (${C.merged.rejected})`);
console.log(`CHAIN letters affected firstRun ${C.firstRun.lettersAffected}/${C.firstRun.letters}; merged ${C.merged.lettersAffected}/${C.merged.letters}`);
if (out.WORD_BOMB_backend.pctRejected != null) console.log(`WORD BOMB (backend, unchanged): ${out.WORD_BOMB_backend.pctRejected}% probe rejected`);
for (const [c, b] of Object.entries(C.merged.byCategory)) console.log(`  ${c}: ${b.rejected}/${b.probe} rejected (merged) ${b.sample.slice(0, 8).join(' ')}`);
if (out.corpusTop25kGap.tokens) console.log(`corpus top-25k tokens rejected: firstRun ${out.corpusTop25kGap.rejectedFirstRun}, merged ${out.corpusTop25kGap.rejectedMerged} (of ${out.corpusTop25kGap.tokens})`);
console.log(`-> ${dest}`);
